### ISSUE TITLE
No 'From' address

### ISSUE THREAD

**Issue by streaps** [iNPUTmice/lttrs-android#44]
I don't know if this is a ltt.rs problem or a problem of the Cyrus jmap server (or my configuration):

If I try to compose a mail, there is no email address in the From field. Ltt.rs expect me to choose one, but it's an empty list.

**Comment by iNPUTmice** [comment]
I think this happens if mailboxes are just usernames but not email addresses. In that case the `getIdentity` call returns empty results. I think @eeeeeta has experienced this before. But I don’t remember the outcome or the resolution if there was any.

**Comment by streaps** [comment]
The user account on my cyrus server is in the form username@sub.domain.tld as I couldn't configure a plain username without the @domain part in ltt.rs.

**Comment by iNPUTmice** [comment]
There are two possibilities:

1) Ltt.rs was unable to fetch your identities when you initially set up the account (Temporary network glitch or something). If that was the case this is fixed in 7230604ea12d5b90b46d187f8f0b11a8bca1d17d - Ltt.rs will update identities any time you open the Compose screen. (An alternative solution would be to add the account again if you are on Ltt.rs <0.3
2) There is something wrong with the Cyrus setup and Cyrus is not returning any Identities. In that case there is nothing Ltt.rs can do about it.

(FWIW I'm reasonably hopeful that it is (1))
